server:
  port: 443
  ssl:
    enabled: true
    key-store: classpath:local-ssl.p12
    key-store-type: PKCS12
    key-store-password: Youdom@,1996
    key-password: Youdom@,1996
    key-alias: local-ssl.p12

spring:
  application:
    name: GATEWAY-SERVICE
    
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedHeaders: '*'
            allowedMethods:
            - POST
            - GET
            - PUT
            - DELETE
            - OPTIONS
            - HEAD

hystrix:
  command:
    fallback:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 4000

management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream


