server:
  port: 9191

spring:
  application:
    name: GATEWAY-SERVICE
    
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedHeaders: '*'
            allowedMethods:
            - POST
            - GET
            - PUT
            - DELETE
            - OPTIONS
            - HEAD

hystrix:
  command:
    fallback:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 4000

management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream


