server:
  port: 443
  ssl:
    enabled: true
    key-store: classpath:keystore.jks 
    key-store-password: 
    key-password: 
    key-alias:

spring:
  application:
    name: GATEWAY-SERVICE
    
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedHeaders: '*'
            allowedMethods:
            - POST
            - GET
            - PUT
            - DELETE
            - OPTIONS
            - HEAD

hystrix:
  command:
    fallback:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 4000

management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream


