server:
  port: 9191

spring:
  application:
    name: GATEWAY-SERVICE
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedHeaders: '*'
            allowedMethods:
            - POST
            - GET
            - PUT
            - DELETE
            - OPTIONS
            - HEAD

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://62.72.0.198:8761/eureka
  instance:
    hostname: 62.72.0.198

hystrix:
  command:
    fallback:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 4000

management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream


